### ISSUE TITLE
Node 0.12 - build failed

### ISSUE THREAD

**Issue by kmalakoff** [arunoda/node-usage#41]
Based on the output, I think this is a problem in node-usage....

157220 verbose stack Error: usage@0.3.10 install: `node-gyp rebuild`
157220 verbose stack Exit status 1
157220 verbose stack     at EventEmitter.<anonymous> (/Users/me/.nvm/versions/node/v0.12.0/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
157220 verbose stack     at EventEmitter.emit (events.js:110:17)
157220 verbose stack     at ChildProcess.<anonymous> (/Users/me/.nvm/versions/node/v0.12.0/lib/node_modules/npm/lib/utils/spawn.js:14:12)
157220 verbose stack     at ChildProcess.emit (events.js:110:17)
157220 verbose stack     at maybeClose (child_process.js:1008:16)
157220 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
157221 verbose pkgid usage@0.3.10

**Comment by TimBeyer** [comment]
@kmalakoff so what was the problem and how was it solved?

**Comment by kmalakoff** [comment]
@TimBeyer I'm sorry, but I don't remember the problem and solution. It might have just gone away on its own.
