### ISSUE TITLE
Install fails under io.js 1.1.0

### ISSUE THREAD

**Issue by goloroden** [arunoda/node-usage#42]
I tried to install `usage` using io.js 1.1.0 (with the official [io.js image for Docker](https://registry.hub.docker.com/_/iojs/)), but unfortunately, it failed :-(

Here's the log:

> $ npm install usage
> \-
> \> usage@0.5.0 install /node_modules/usage
> \> node-gyp rebuild
> 
> child_process: customFds option is deprecated, use stdio instead.
> make: Entering directory '/node_modules/usage/build'
>   CXX(target) Release/obj.target/sysinfo/src/binding.o
> In file included from ../src/binding.cpp:2:0:
> ../node_modules/nan/nan.h:481:19: error: 'NanNew' declared as an 'inline' variable
>        v8::String::ExternalAsciiStringResource *resource) {
>                    ^
> ../node_modules/nan/nan.h:481:19: warning: 'always_inline' attribute ignored [-Wattributes]
> ../node_modules/nan/nan.h:481:19: error: 'v8::Local<v8::String> NanNew' redeclared as different kind of symbol
> ../node_modules/nan/nan.h:475:36: note: previous declaration 'v8::Local<v8::String> NanNew(v8::String::ExternalStringResource*)'
>    NAN_INLINE v8::Local<v8::String> NanNew(
>                                     ^
> ../node_modules/nan/nan.h:481:7: error: 'ExternalAsciiStringResource' is not a member of 'v8::String'
>        v8::String::ExternalAsciiStringResource *resource) {
>        ^
> ../node_modules/nan/nan.h:481:48: error: 'resource' was not declared in this scope
>        v8::String::ExternalAsciiStringResource *resource) {
>                                                 ^
> ../node_modules/nan/nan.h: In function 'bool _NanGetExternalParts(v8::Handle<v8::Value>, const char**, size_t*)':
> ../node_modules/nan/nan.h:2103:12: error: 'class v8::String' has no member named 'IsExternalAscii'
>    if (str->IsExternalAscii()) {
>             ^
> ../node_modules/nan/nan.h:2104:23: error: 'ExternalAsciiStringResource' in 'class v8::String' does not name a type
>      const v8::String::ExternalAsciiStringResource* ext;
>                        ^
> ../node_modules/nan/nan.h:2105:5: error: 'ext' was not declared in this scope
>      ext = str->GetExternalAsciiStringResource();
>      ^
> ../node_modules/nan/nan.h:2105:16: error: 'class v8::String' has no member named 'GetExternalAsciiStringResource'
>      ext = str->GetExternalAsciiStringResource();
>                 ^
> sysinfo.target.mk:90: recipe for target 'Release/obj.target/sysinfo/src/binding.o' failed
> make: *** [Release/obj.target/sysinfo/src/binding.o] Error 1
> make: Leaving directory '/node_modules/usage/build'
> gyp ERR! build error 
> gyp ERR! stack Error: `make` failed with exit code: 2
> gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
> gyp ERR! stack     at ChildProcess.emit (events.js:100:17)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1040:12)
> gyp ERR! System Linux 3.18.5-tinycore64
> gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
> gyp ERR! cwd /node_modules/usage
> gyp ERR! node -v v1.1.0
> gyp ERR! node-gyp -v v1.0.2
> gyp ERR! not ok 
> npm ERR! Linux 3.18.5-tinycore64
> npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "install" "usage"
> npm ERR! node v1.1.0
> npm ERR! npm  v2.4.1
> npm ERR! code ELIFECYCLE
> 
> npm ERR! usage@0.5.0 install: `node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the usage@0.5.0 install script 'node-gyp rebuild'.
> npm ERR! This is most likely a problem with the usage package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node-gyp rebuild
> npm ERR! You can get their info via:
> npm ERR!     npm owner ls usage
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /npm-debug.log

**Comment by achingbrain** [comment]
io.js support is a little ropey right now due to dependencies that use native modules, hopefully this will get better over time as people update their code.  Have you tried io.js 1.2.0?

**Comment by goloroden** [comment]
I now also tried it using io.js 1.2.0, same result :-(

**Comment by goloroden** [comment]
Solved by 0.6.0. Thanks a lot for this extremely fast solution :-))
